dependencies:
  - numpy
  - scipy.integrate
  - scipy.optimize
  - scipy.interpolate
  - IPython.display
  - mpl_toolkits
  - matplotlib
  - ipywidgets
  - pandas
  - warnings 
  - REE_ED_Takahashi_Model
